version: '3.9'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data: